spec:x86_64:
  script:
    - cd build
    - CXX=clang++ cmake .. -DCPA_SKIP_RUN_UNIT_TESTS=On
    - make -j$(nproc)
    - ctest --output-on-failure
  tags:
    - x86_64
    - cxx14
    - clang
  artifacts:
    paths:
      - build/products
      - build/cute-reports

spec:arm:
  script:
    - cd build
    - CXX=clang++ cmake .. -DCPA_SKIP_RUN_UNIT_TESTS=On
    - make -j$(nproc)
    - ctest --output-on-failure
  tags:
    - arm
    - cxx14
    - clang
  artifacts:
    paths:
      - build/products
      - build/cute-reports
